Tests 100%
xynga/form-elements pull request #9
Opened 2018-02-13 19:48 UTC by timjklein36

Added test for all then components and achieved 100% code coverage.

![image](https://user-images.githubusercontent.com/10482910/36170273-e8b271a4-10cc-11e8-884c-79df75107d14.png)

2018-02-13 19:50 UTC, timjklein36 commented
For clarity: 100% Unit tests using Karma

2018-02-19 15:50 UTC, nseanac requested changes
angular-cli version needs to be bumped up (same issue as table)

2018-03-15 19:34 UTC, pavinkjr commented
I added the e2e tests and updated the cli version.

2018-03-16 15:50 UTC, nseanac approved these changes

2018-03-16 15:50 UTC, merged